-- =============================================================================================
-- Configuration Tables for P1_MAIN_SYS_INTERFACES_TE
-- Purpose: Eliminate hardcoded values and make the system configurable
-- =============================================================================================

-- =============================================================================================
-- Table: P1_APN_CONFIG_TE
-- Purpose: Configure APN IDs and their descriptions
-- =============================================================================================
CREATE TABLE P1_APN_CONFIG_TE (
    APN_ID              VARCHAR2(10) PRIMARY KEY,
    APN_NAME            VARCHAR2(100) NOT NULL,
    APN_DESCRIPTION     VARCHAR2(200),
    COMPANION_PRODUCT   VARCHAR2(100),
    PRIORITY_ORDER      NUMBER,
    ACTIVE_FLAG         VARCHAR2(1) DEFAULT 'Y',
    CREATED_DATE        DATE DEFAULT SYSDATE,
    MODIFIED_DATE       DATE DEFAULT SYSDATE
);

-- Insert APN configurations
INSERT INTO P1_APN_CONFIG_TE (APN_ID, APN_NAME, APN_DESCRIPTION, COMPANION_PRODUCT, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('20', 'WLL_APN', 'Wireless Local Loop APN', 'Mobile Internet WLL', 1, 'Y');

INSERT INTO P1_APN_CONFIG_TE (APN_ID, APN_NAME, APN_DESCRIPTION, COMPANION_PRODUCT, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('15', 'ALFA_APN', 'Alfa APN', 'Alfa APN', 2, 'Y');

INSERT INTO P1_APN_CONFIG_TE (APN_ID, APN_NAME, APN_DESCRIPTION, COMPANION_PRODUCT, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('13', 'MBB_APN', 'Mobile BroadBand APN', 'Mobile BroadBand', 3, 'Y');

INSERT INTO P1_APN_CONFIG_TE (APN_ID, APN_NAME, APN_DESCRIPTION, COMPANION_PRODUCT, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('12', 'BLACKBERRY_APN', 'Blackberry APN', 'Blackberry', 4, 'Y');

INSERT INTO P1_APN_CONFIG_TE (APN_ID, APN_NAME, APN_DESCRIPTION, COMPANION_PRODUCT, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('10', 'GPRS_INTRA_APN', 'GPRS Intranet APN', 'GPRS INTRA', 5, 'Y');

INSERT INTO P1_APN_CONFIG_TE (APN_ID, APN_NAME, APN_DESCRIPTION, COMPANION_PRODUCT, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('9', 'MMS_APN', 'MMS APN', 'MMS', 6, 'Y');

INSERT INTO P1_APN_CONFIG_TE (APN_ID, APN_NAME, APN_DESCRIPTION, COMPANION_PRODUCT, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('8', 'WAP_APN', 'WAP APN', 'WAP', 7, 'Y');

INSERT INTO P1_APN_CONFIG_TE (APN_ID, APN_NAME, APN_DESCRIPTION, COMPANION_PRODUCT, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('7', 'GPRS_APN', 'GPRS APN', 'GPRS', 8, 'Y');

INSERT INTO P1_APN_CONFIG_TE (APN_ID, APN_NAME, APN_DESCRIPTION, COMPANION_PRODUCT, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('3', 'DATACARD1_APN', 'Data Card Type 1 APN', 'Data Card', 9, 'Y');

INSERT INTO P1_APN_CONFIG_TE (APN_ID, APN_NAME, APN_DESCRIPTION, COMPANION_PRODUCT, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('4', 'DATACARD2_APN', 'Data Card Type 2 APN', 'Data Card', 10, 'Y');

INSERT INTO P1_APN_CONFIG_TE (APN_ID, APN_NAME, APN_DESCRIPTION, COMPANION_PRODUCT, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('6', 'DATACARD3_APN', 'Data Card Type 3 APN', 'Data Card', 11, 'Y');

INSERT INTO P1_APN_CONFIG_TE (APN_ID, APN_NAME, APN_DESCRIPTION, COMPANION_PRODUCT, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('94', 'VOLTE01_APN', 'VoLTE Type 1 APN', 'Volte', 12, 'Y');

INSERT INTO P1_APN_CONFIG_TE (APN_ID, APN_NAME, APN_DESCRIPTION, COMPANION_PRODUCT, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES ('95', 'VOLTE02_APN', 'VoLTE Type 2 APN', 'Volte', 13, 'Y');

COMMIT;

-- =============================================================================================
-- Table: P1_SDP_ROUTING_CONFIG_TE
-- Purpose: Configure SDP routing based on MSISDN ranges
-- =============================================================================================
CREATE TABLE P1_SDP_ROUTING_CONFIG_TE (
    RANGE_ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MSISDN_RANGE_START  NUMBER NOT NULL,
    MSISDN_RANGE_END    NUMBER NOT NULL,
    SDP_NAME            VARCHAR2(50) NOT NULL,
    SDP_DESCRIPTION     VARCHAR2(200),
    PRIORITY_ORDER      NUMBER,
    ACTIVE_FLAG         VARCHAR2(1) DEFAULT 'Y',
    CREATED_DATE        DATE DEFAULT SYSDATE,
    MODIFIED_DATE       DATE DEFAULT SYSDATE
);

-- Insert SDP routing configurations
INSERT INTO P1_SDP_ROUTING_CONFIG_TE (MSISDN_RANGE_START, MSISDN_RANGE_END, SDP_NAME, SDP_DESCRIPTION, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES (71900000, 71999999, 'SDP05', 'SDP05 Range 719xxxxx', 1, 'Y');

INSERT INTO P1_SDP_ROUTING_CONFIG_TE (MSISDN_RANGE_START, MSISDN_RANGE_END, SDP_NAME, SDP_DESCRIPTION, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES (71800000, 71899999, 'SDP06', 'SDP06 Range 718xxxxx', 2, 'Y');

INSERT INTO P1_SDP_ROUTING_CONFIG_TE (MSISDN_RANGE_START, MSISDN_RANGE_END, SDP_NAME, SDP_DESCRIPTION, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES (3000000, 3999999, 'SDP03', 'SDP03 Range 3xxxxxx', 3, 'Y');

INSERT INTO P1_SDP_ROUTING_CONFIG_TE (MSISDN_RANGE_START, MSISDN_RANGE_END, SDP_NAME, SDP_DESCRIPTION, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES (70000000, 70999999, 'SDP04', 'SDP04 Range 70xxxxxx', 4, 'Y');

INSERT INTO P1_SDP_ROUTING_CONFIG_TE (MSISDN_RANGE_START, MSISDN_RANGE_END, SDP_NAME, SDP_DESCRIPTION, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES (71000000, 71099999, 'SDP04', 'SDP04 Range 710xxxxx', 5, 'Y');

INSERT INTO P1_SDP_ROUTING_CONFIG_TE (MSISDN_RANGE_START, MSISDN_RANGE_END, SDP_NAME, SDP_DESCRIPTION, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES (76100000, 76199999, 'SDP05', 'SDP05 Range 761xxxxx', 6, 'Y');

INSERT INTO P1_SDP_ROUTING_CONFIG_TE (MSISDN_RANGE_START, MSISDN_RANGE_END, SDP_NAME, SDP_DESCRIPTION, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES (71600000, 71699999, 'SDP04', 'SDP04 Range 716xxxxx', 7, 'Y');

INSERT INTO P1_SDP_ROUTING_CONFIG_TE (MSISDN_RANGE_START, MSISDN_RANGE_END, SDP_NAME, SDP_DESCRIPTION, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES (71700000, 71799999, 'SDP05', 'SDP05 Range 717xxxxx', 8, 'Y');

INSERT INTO P1_SDP_ROUTING_CONFIG_TE (MSISDN_RANGE_START, MSISDN_RANGE_END, SDP_NAME, SDP_DESCRIPTION, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES (76300000, 76399999, 'SDP05', 'SDP05 Range 763xxxxx', 9, 'Y');

INSERT INTO P1_SDP_ROUTING_CONFIG_TE (MSISDN_RANGE_START, MSISDN_RANGE_END, SDP_NAME, SDP_DESCRIPTION, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES (76400000, 76499999, 'SDP06', 'SDP06 Range 764xxxxx', 10, 'Y');

INSERT INTO P1_SDP_ROUTING_CONFIG_TE (MSISDN_RANGE_START, MSISDN_RANGE_END, SDP_NAME, SDP_DESCRIPTION, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES (76500000, 76599999, 'SDP05', 'SDP05 Range 765xxxxx', 11, 'Y');

INSERT INTO P1_SDP_ROUTING_CONFIG_TE (MSISDN_RANGE_START, MSISDN_RANGE_END, SDP_NAME, SDP_DESCRIPTION, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES (79100000, 79199999, 'SDP06', 'SDP06 Range 791xxxxx', 12, 'Y');

INSERT INTO P1_SDP_ROUTING_CONFIG_TE (MSISDN_RANGE_START, MSISDN_RANGE_END, SDP_NAME, SDP_DESCRIPTION, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES (79300000, 79324999, 'SDP06', 'SDP06 Range 7930xxxx-7932xxxx', 13, 'Y');

INSERT INTO P1_SDP_ROUTING_CONFIG_TE (MSISDN_RANGE_START, MSISDN_RANGE_END, SDP_NAME, SDP_DESCRIPTION, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES (1000000, 1999999, 'SDP06', 'SDP06 Range 1xxxxxx', 14, 'Y');

INSERT INTO P1_SDP_ROUTING_CONFIG_TE (MSISDN_RANGE_START, MSISDN_RANGE_END, SDP_NAME, SDP_DESCRIPTION, PRIORITY_ORDER, ACTIVE_FLAG)
VALUES (81000000, 81999999, 'SDP05', 'SDP05 Range 81xxxxxx', 15, 'Y');

COMMIT;

-- =============================================================================================
-- Table: P1_HLR_CONFIG_TE
-- Purpose: Configure HLR identification based on IMSI prefixes
-- =============================================================================================
CREATE TABLE P1_HLR_CONFIG_TE (
    IMSI_PREFIX         VARCHAR2(10) PRIMARY KEY,
    HLR_NUMBER          NUMBER NOT NULL,
    HLR_NAME            VARCHAR2(50),
    HLR_DESCRIPTION     VARCHAR2(200),
    ACTIVE_FLAG         VARCHAR2(1) DEFAULT 'Y',
    CREATED_DATE        DATE DEFAULT SYSDATE,
    MODIFIED_DATE       DATE DEFAULT SYSDATE
);

-- Insert HLR configurations
INSERT INTO P1_HLR_CONFIG_TE (IMSI_PREFIX, HLR_NUMBER, HLR_NAME, HLR_DESCRIPTION, ACTIVE_FLAG)
VALUES ('415012', 1, 'HLR1_PRIMARY', 'Primary HLR1 IMSI Prefix', 'Y');

INSERT INTO P1_HLR_CONFIG_TE (IMSI_PREFIX, HLR_NUMBER, HLR_NAME, HLR_DESCRIPTION, ACTIVE_FLAG)
VALUES ('415019', 1, 'HLR1_SECONDARY', 'Secondary HLR1 IMSI Prefix', 'Y');

INSERT INTO P1_HLR_CONFIG_TE (IMSI_PREFIX, HLR_NUMBER, HLR_NAME, HLR_DESCRIPTION, ACTIVE_FLAG)
VALUES ('415018', 0, 'HLR_EXCLUDED', 'Excluded IMSI Prefix', 'Y');

COMMIT;

-- =============================================================================================
-- Table: P1_PRODUCT_CONFIG_TE
-- Purpose: Configure product types and rate plans for MISP filtering
-- =============================================================================================
CREATE TABLE P1_PRODUCT_CONFIG_TE (
    CONFIG_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_TYPE_NAME   VARCHAR2(100),
    RATE_PLAN           NUMBER,
    CATEGORY            VARCHAR2(50),
    DESCRIPTION         VARCHAR2(200),
    ACTIVE_FLAG         VARCHAR2(1) DEFAULT 'Y',
    CREATED_DATE        DATE DEFAULT SYSDATE,
    MODIFIED_DATE       DATE DEFAULT SYSDATE
);

-- Insert Product configurations for MISP
INSERT INTO P1_PRODUCT_CONFIG_TE (PRODUCT_TYPE_NAME, RATE_PLAN, CATEGORY, DESCRIPTION, ACTIVE_FLAG)
VALUES ('Mobile Broadband Prepaid', 31, 'MISP', 'MISP Rate Plan 31', 'Y');

INSERT INTO P1_PRODUCT_CONFIG_TE (PRODUCT_TYPE_NAME, RATE_PLAN, CATEGORY, DESCRIPTION, ACTIVE_FLAG)
VALUES ('Mobile Broadband Prepaid', 33, 'MISP', 'MISP Rate Plan 33', 'Y');

INSERT INTO P1_PRODUCT_CONFIG_TE (PRODUCT_TYPE_NAME, RATE_PLAN, CATEGORY, DESCRIPTION, ACTIVE_FLAG)
VALUES ('Mobile Broadband Prepaid', 30, 'MISP', 'MISP Rate Plan 30', 'Y');

INSERT INTO P1_PRODUCT_CONFIG_TE (PRODUCT_TYPE_NAME, RATE_PLAN, CATEGORY, DESCRIPTION, ACTIVE_FLAG)
VALUES ('Mobile Broadband Prepaid', 34, 'MISP', 'MISP Rate Plan 34', 'Y');

INSERT INTO P1_PRODUCT_CONFIG_TE (PRODUCT_TYPE_NAME, RATE_PLAN, CATEGORY, DESCRIPTION, ACTIVE_FLAG)
VALUES ('Mobile Broadband Prepaid', 32, 'MISP', 'MISP Rate Plan 32', 'Y');

INSERT INTO P1_PRODUCT_CONFIG_TE (PRODUCT_TYPE_NAME, RATE_PLAN, CATEGORY, DESCRIPTION, ACTIVE_FLAG)
VALUES ('Mobile Broadband Prepaid', 35, 'MISP', 'MISP Rate Plan 35', 'Y');

INSERT INTO P1_PRODUCT_CONFIG_TE (PRODUCT_TYPE_NAME, RATE_PLAN, CATEGORY, DESCRIPTION, ACTIVE_FLAG)
VALUES ('Mobile Broadband Prepaid', 36, 'MISP', 'MISP Rate Plan 36', 'Y');

INSERT INTO P1_PRODUCT_CONFIG_TE (PRODUCT_TYPE_NAME, RATE_PLAN, CATEGORY, DESCRIPTION, ACTIVE_FLAG)
VALUES ('Mobile Broadband Prepaid', 37, 'MISP', 'MISP Rate Plan 37', 'Y');

INSERT INTO P1_PRODUCT_CONFIG_TE (PRODUCT_TYPE_NAME, RATE_PLAN, CATEGORY, DESCRIPTION, ACTIVE_FLAG)
VALUES ('Mobile Broadband Prepaid', 38, 'MISP', 'MISP Rate Plan 38', 'Y');

INSERT INTO P1_PRODUCT_CONFIG_TE (PRODUCT_TYPE_NAME, RATE_PLAN, CATEGORY, DESCRIPTION, ACTIVE_FLAG)
VALUES ('Mobile Broadband Prepaid', 59, 'MISP', 'MISP Rate Plan 59', 'Y');

COMMIT;

-- =============================================================================================
-- Table: P1_SYSTEM_CONFIG_TE
-- Purpose: General system configuration parameters
-- =============================================================================================
CREATE TABLE P1_SYSTEM_CONFIG_TE (
    CONFIG_KEY          VARCHAR2(100) PRIMARY KEY,
    CONFIG_VALUE        VARCHAR2(500),
    CONFIG_TYPE         VARCHAR2(50),
    DESCRIPTION         VARCHAR2(200),
    ACTIVE_FLAG         VARCHAR2(1) DEFAULT 'Y',
    CREATED_DATE        DATE DEFAULT SYSDATE,
    MODIFIED_DATE       DATE DEFAULT SYSDATE
);

-- Insert system configurations
INSERT INTO P1_SYSTEM_CONFIG_TE (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION, ACTIVE_FLAG)
VALUES ('DEFAULT_SDP', 'SDP', 'STRING', 'Default SDP when MSISDN range not found', 'Y');

INSERT INTO P1_SYSTEM_CONFIG_TE (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION, ACTIVE_FLAG)
VALUES ('DEFAULT_HLR', '2', 'NUMBER', 'Default HLR number when IMSI prefix not found', 'Y');

INSERT INTO P1_SYSTEM_CONFIG_TE (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION, ACTIVE_FLAG)
VALUES ('ENABLE_ACTIVITY_TRACE', 'Y', 'BOOLEAN', 'Enable/Disable activity tracing', 'Y');

INSERT INTO P1_SYSTEM_CONFIG_TE (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION, ACTIVE_FLAG)
VALUES ('NOLOGGING_MODE', 'Y', 'BOOLEAN', 'Create tables with NOLOGGING option', 'Y');

INSERT INTO P1_SYSTEM_CONFIG_TE (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION, ACTIVE_FLAG)
VALUES ('DEFAULT_SCHEMA', 'FAFIF', 'STRING', 'Default schema for table creation', 'Y');

INSERT INTO P1_SYSTEM_CONFIG_TE (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION, ACTIVE_FLAG)
VALUES ('EXPORT_ENABLED', 'Y', 'BOOLEAN', 'Enable/Disable export to ADM', 'Y');

INSERT INTO P1_SYSTEM_CONFIG_TE (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION, ACTIVE_FLAG)
VALUES ('TRACE_RETENTION_DAYS', '90', 'NUMBER', 'Days to retain activity trace records', 'Y');

COMMIT;

-- =============================================================================================
-- Create indexes for performance
-- =============================================================================================
CREATE INDEX IX_SDP_ROUTING_RANGE_TE ON P1_SDP_ROUTING_CONFIG_TE(MSISDN_RANGE_START, MSISDN_RANGE_END);
CREATE INDEX IX_SDP_ROUTING_ACTIVE_TE ON P1_SDP_ROUTING_CONFIG_TE(ACTIVE_FLAG);
CREATE INDEX IX_PRODUCT_CONFIG_ACTIVE_TE ON P1_PRODUCT_CONFIG_TE(ACTIVE_FLAG);
CREATE INDEX IX_PRODUCT_CONFIG_RATE_TE ON P1_PRODUCT_CONFIG_TE(RATE_PLAN);

-- =============================================================================================
-- Create view for easy access to active configurations
-- =============================================================================================
CREATE OR REPLACE VIEW V_P1_ACTIVE_CONFIG_TE AS
SELECT
    'APN' as CONFIG_TYPE,
    APN_ID as CONFIG_KEY,
    APN_NAME as CONFIG_VALUE,
    APN_DESCRIPTION as DESCRIPTION
FROM P1_APN_CONFIG_TE
WHERE ACTIVE_FLAG = 'Y'
UNION ALL
SELECT
    'SDP_ROUTING' as CONFIG_TYPE,
    TO_CHAR(RANGE_ID) as CONFIG_KEY,
    SDP_NAME as CONFIG_VALUE,
    SDP_DESCRIPTION as DESCRIPTION
FROM P1_SDP_ROUTING_CONFIG_TE
WHERE ACTIVE_FLAG = 'Y'
UNION ALL
SELECT
    'HLR' as CONFIG_TYPE,
    IMSI_PREFIX as CONFIG_KEY,
    HLR_NAME as CONFIG_VALUE,
    HLR_DESCRIPTION as DESCRIPTION
FROM P1_HLR_CONFIG_TE
WHERE ACTIVE_FLAG = 'Y'
UNION ALL
SELECT
    'PRODUCT' as CONFIG_TYPE,
    TO_CHAR(CONFIG_ID) as CONFIG_KEY,
    PRODUCT_TYPE_NAME || ' - ' || TO_CHAR(RATE_PLAN) as CONFIG_VALUE,
    DESCRIPTION
FROM P1_PRODUCT_CONFIG_TE
WHERE ACTIVE_FLAG = 'Y'
UNION ALL
SELECT
    'SYSTEM' as CONFIG_TYPE,
    CONFIG_KEY,
    CONFIG_VALUE,
    DESCRIPTION
FROM P1_SYSTEM_CONFIG_TE
WHERE ACTIVE_FLAG = 'Y';

COMMIT;
